// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImgPackageClass.proto

package com.microport.httpserver.protobuf;

public final class ImgPackageClass {
  private ImgPackageClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImagePackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.microport.adbusb.protobuf.ImagePackage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 index = 1;</code>
     * @return The index.
     */
    long getIndex();

    /**
     * <code>uint64 st = 2;</code>
     * @return The st.
     */
    long getSt();

    /**
     * <code>bytes imgData = 3;</code>
     * @return The imgData.
     */
    com.google.protobuf.ByteString getImgData();
  }
  /**
   * Protobuf type {@code com.microport.adbusb.protobuf.ImagePackage}
   */
  public static final class ImagePackage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.microport.adbusb.protobuf.ImagePackage)
      ImagePackageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImagePackage.newBuilder() to construct.
    private ImagePackage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImagePackage() {
      imgData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ImagePackage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImagePackage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              index_ = input.readUInt64();
              break;
            }
            case 16: {

              st_ = input.readUInt64();
              break;
            }
            case 26: {

              imgData_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microport.httpserver.protobuf.ImgPackageClass.internal_static_com_microport_adbusb_protobuf_ImagePackage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microport.httpserver.protobuf.ImgPackageClass.internal_static_com_microport_adbusb_protobuf_ImagePackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage.class, com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage.Builder.class);
    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private long index_;
    /**
     * <code>uint64 index = 1;</code>
     * @return The index.
     */
    @java.lang.Override
    public long getIndex() {
      return index_;
    }

    public static final int ST_FIELD_NUMBER = 2;
    private long st_;
    /**
     * <code>uint64 st = 2;</code>
     * @return The st.
     */
    @java.lang.Override
    public long getSt() {
      return st_;
    }

    public static final int IMGDATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString imgData_;
    /**
     * <code>bytes imgData = 3;</code>
     * @return The imgData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getImgData() {
      return imgData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (index_ != 0L) {
        output.writeUInt64(1, index_);
      }
      if (st_ != 0L) {
        output.writeUInt64(2, st_);
      }
      if (!imgData_.isEmpty()) {
        output.writeBytes(3, imgData_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, index_);
      }
      if (st_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, st_);
      }
      if (!imgData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, imgData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage)) {
        return super.equals(obj);
      }
      com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage other = (com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage) obj;

      if (getIndex()
          != other.getIndex()) return false;
      if (getSt()
          != other.getSt()) return false;
      if (!getImgData()
          .equals(other.getImgData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIndex());
      hash = (37 * hash) + ST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSt());
      hash = (37 * hash) + IMGDATA_FIELD_NUMBER;
      hash = (53 * hash) + getImgData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.microport.adbusb.protobuf.ImagePackage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.microport.adbusb.protobuf.ImagePackage)
        com.microport.httpserver.protobuf.ImgPackageClass.ImagePackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.microport.httpserver.protobuf.ImgPackageClass.internal_static_com_microport_adbusb_protobuf_ImagePackage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.microport.httpserver.protobuf.ImgPackageClass.internal_static_com_microport_adbusb_protobuf_ImagePackage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage.class, com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage.Builder.class);
      }

      // Construct using com.microport.adbusb.protobuf.ImgPackageClass.ImagePackage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        index_ = 0L;

        st_ = 0L;

        imgData_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.microport.httpserver.protobuf.ImgPackageClass.internal_static_com_microport_adbusb_protobuf_ImagePackage_descriptor;
      }

      @java.lang.Override
      public com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage getDefaultInstanceForType() {
        return com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage.getDefaultInstance();
      }

      @java.lang.Override
      public com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage build() {
        com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage buildPartial() {
        com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage result = new com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage(this);
        result.index_ = index_;
        result.st_ = st_;
        result.imgData_ = imgData_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage) {
          return mergeFrom((com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage other) {
        if (other == com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage.getDefaultInstance()) return this;
        if (other.getIndex() != 0L) {
          setIndex(other.getIndex());
        }
        if (other.getSt() != 0L) {
          setSt(other.getSt());
        }
        if (other.getImgData() != com.google.protobuf.ByteString.EMPTY) {
          setImgData(other.getImgData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long index_ ;
      /**
       * <code>uint64 index = 1;</code>
       * @return The index.
       */
      @java.lang.Override
      public long getIndex() {
        return index_;
      }
      /**
       * <code>uint64 index = 1;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(long value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 index = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        
        index_ = 0L;
        onChanged();
        return this;
      }

      private long st_ ;
      /**
       * <code>uint64 st = 2;</code>
       * @return The st.
       */
      @java.lang.Override
      public long getSt() {
        return st_;
      }
      /**
       * <code>uint64 st = 2;</code>
       * @param value The st to set.
       * @return This builder for chaining.
       */
      public Builder setSt(long value) {
        
        st_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 st = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSt() {
        
        st_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString imgData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes imgData = 3;</code>
       * @return The imgData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getImgData() {
        return imgData_;
      }
      /**
       * <code>bytes imgData = 3;</code>
       * @param value The imgData to set.
       * @return This builder for chaining.
       */
      public Builder setImgData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imgData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes imgData = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearImgData() {
        
        imgData_ = getDefaultInstance().getImgData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.microport.adbusb.protobuf.ImagePackage)
    }

    // @@protoc_insertion_point(class_scope:com.microport.adbusb.protobuf.ImagePackage)
    private static final com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage();
    }

    public static com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImagePackage>
        PARSER = new com.google.protobuf.AbstractParser<ImagePackage>() {
      @java.lang.Override
      public ImagePackage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImagePackage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImagePackage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImagePackage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.microport.httpserver.protobuf.ImgPackageClass.ImagePackage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_microport_adbusb_protobuf_ImagePackage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_microport_adbusb_protobuf_ImagePackage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ImgPackageClass.proto\022\035com.microport.a" +
      "dbusb.protobuf\":\n\014ImagePackage\022\r\n\005index\030" +
      "\001 \001(\004\022\n\n\002st\030\002 \001(\004\022\017\n\007imgData\030\003 \001(\014b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_microport_adbusb_protobuf_ImagePackage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_microport_adbusb_protobuf_ImagePackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_microport_adbusb_protobuf_ImagePackage_descriptor,
        new java.lang.String[] { "Index", "St", "ImgData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
